version: 2.1
tagged_build_filters: &tagged_build_filters
  branches:
    ignore: /.*/
  tags:
    only: /v[0-9]+\.[0-9]+\.[0-9]+/
test_build_filters: &test_build_filters
  branches:
    only: /.*/
  tags:
    ignore: /v[0-9]+\.[0-9]+\.[0-9]+/
executors:
  releaser:
    docker:
      - image: circleci/golang:1.12
  ruby265:
    docker:
      - image: circleci/ruby:2.6.5
  ruby23:
    docker:
      - image: circleci/ruby:2.3
jobs:
  test:
    parameters:
      ruby:
        type: executor
    executor: << parameters.ruby >>
    steps:
      - checkout
      - run: bundle install
      - run: rubocop -c .rubocop.yml
      - run: rake test
  build:
    executor: ruby265
    steps:
      - checkout
      - run:
          name: Check Tagged Push
          command: |
            PKG_VERSION=$(cat fluent-plugin-logdna.gemspec | grep "\.version" | cut -d'"' -f2)
            if [[ "${CIRCLE_TAG}" != "v${PKG_VERSION}" ]]; then
              echo "There is mismatch:"
              echo "  TAG_VERSION: ${CIRCLE_TAG}"
              echo "  PKG_VERSION: v${PKG_VERSION}"
              exit 1
            fi
      - run: gem build fluent-plugin-logdna.gemspec
      - persist_to_workspace:
          root: .
          paths:
            - ./fluent-plugin-logdna-*.gem
  release:
    executor: releaser
    steps:
      - attach_workspace:
          at: .
      - run: go get -u github.com/tcnksm/ghr
      - run:
          name: Create a Release
          command: |
            ghr \
              -n "LogDNA Fluentd Plugin ${CIRCLE_TAG}" \
              -t ${GITHUB_TOKEN} \
              -u ${CIRCLE_PROJECT_USERNAME} \
              -r ${CIRCLE_PROJECT_REPONAME} \
              -draft ${CIRCLE_TAG} ./
      - persist_to_workspace:
          root: .
          paths:
            - ./fluent-plugin-logdna-*.gem
  approve:
    machine: true
    steps:
      - attach_workspace:
          at: .
      - persist_to_workspace:
          root: .
          paths:
            - ./fluent-plugin-logdna-*.gem
  publish:
    executor: ruby265
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Setup gem credentials
          command: |
            mkdir -p ~/.gem
            cat \<<EOF > ~/.gem/credentials
            ---
            :rubygems_api_key: ${RUBYGEMS_API_KEY}
            EOF
            chmod 0600 ~/.gem/credentials
      - run: gem push *.gem
workflows:
  update:
    jobs:
      - test:
          matrix:
            parameters:
              ruby: [ruby23, ruby265]
          filters: *tagged_build_filters
      - build:
          requires:
            - test
          filters: *tagged_build_filters
      - release:
          requires:
            - build
          filters: *tagged_build_filters
      - approve:
          type: approval
          requires:
            - release
          filters: *tagged_build_filters
      - publish:
          requires:
            - approve
          filters: *tagged_build_filters
  test:
    jobs:
      - test:
          matrix:
            parameters:
              ruby: [ruby23, ruby265]
          filters: *test_build_filters
